/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsExports = {
    Auth:{
        Cognito: {
            region: "us-west-1",
            userPoolId: "us-west-1_CPUFWalUJ",
            userPoolClientId: "1nksb11gpfjnb2cu05odo3k9iq",
        }
    },

    /* "aws_project_region": "us-west-1",
    "aws_cognito_region": "us-west-1",
    "aws_user_pools_id": "us-west-1_CPUFWalUJ",
    "aws_user_pools_web_client_id": "1nksb11gpfjnb2cu05odo3k9iq", // client id
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "GIVEN_NAME",
        "FAMILY_NAME"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_UPPERCASE",
            "REQUIRES_NUMBERS"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ] */
};


export default awsExports;
/* {
    "aws_project_region": "us-east-1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-west-1_CPUFWalUJ",
    "aws_user_pools_web_client_id": "1nksb11gpfjnb2cu05odo3k9iq",
} */